/**:
  ros__parameters:
    racing_simulator:
      dt: 0.1
      repeat_state_dt: 0.1
      publish_tf: true
      visualize_boundary: true
      visualize_abscissa: true
      visualize_vehicle: true
      x0: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
