/**:
  ros__parameters:
    single_track_planar:
      fd_max: 15.0 # max driving force
      fb_max: -15.0 # max brake force
      td: 0.1 # time constant for throttle
      tb: 0.1 # time constant for brake
      v_max: 5.0 # max velocity constraint
      p_max: 550.0 # max engine power
      mu: 0.9 # track - tyre friction coefficient
      simplify_lon_control: true # whether to combine brake and throttle into a single variable
