/**:
  ros__parameters:
    racing_mpc:
      max_cpu_time: 10.0
      tol: 0.1
      constr_viol_tol: 0.1
      n: 20
      margin: 0.1
      average_track_width: 4.0
      verbose: false

      q_contour: 0.1
      q_progress: 1.0
      r: [
        0.0, 0.0, 0.0,
        0.0, 0.0, 0.0,
        0.0, 0.0, 0.0
      ]

      x_max: [.inf, .inf, .inf, 1.5, 0.5236, 25.0]
      x_min: [-.inf, -.inf, -.inf, -1.5, -0.5236, 0.0]
      u_max: [1000.0, 0.0, 0.314159]
      u_min: [0.0, -2000.0, -0.314159]
